name: Build Flatpak

on:
  push:
    tags:
      - 'v*'
  pull_request:
    paths:
      - 'flatpak/**'
      - '.github/workflows/flatpak.yml'

jobs:
  validate:
    name: Validate Flatpak Manifest
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y flatpak flatpak-builder
        
    - name: Add Flathub repository
      run: |
        flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        
    - name: Install Wine runtime
      run: |
        flatpak install -y flathub org.winehq.Platform//9 org.winehq.Sdk//9 org.winehq.Platform.Compat.i386//9
        
    - name: Validate manifest
      run: |
        flatpak-builder --dry-run build-dir flatpak/io.github.Snickerstream.yml

  build:
    name: Build Flatpak Bundle
    runs-on: ubuntu-latest
    needs: validate
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y flatpak flatpak-builder
        
    - name: Add Flathub repository
      run: |
        flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        
    - name: Install Wine runtime
      run: |
        flatpak install -y flathub org.winehq.Platform//9 org.winehq.Sdk//9 org.winehq.Platform.Compat.i386//9
        
    - name: Build Flatpak
      run: |
        flatpak-builder --repo=repo build-dir flatpak/io.github.Snickerstream.yml
        
    - name: Create bundle
      run: |
        flatpak build-bundle repo Snickerstream.flatpak io.github.Snickerstream
        
    - name: Create flatpakref
      run: |
        cat > Snickerstream.flatpakref << EOF
        [Flatpak Ref]
        Title=Snickerstream
        Name=io.github.Snickerstream
        Branch=stable
        Url=https://github.com/Arisaya1/Snickerstream/releases/latest/download/
        IsRuntime=false
        Comment=Nintendo 3DS streaming client for NTR CFW and HzMod
        Icon=io.github.Snickerstream
        EOF
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: flatpak-bundle
        path: |
          Snickerstream.flatpak
          Snickerstream.flatpakref
          
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          Snickerstream.flatpak
          Snickerstream.flatpakref
        body: |
          ## Flatpak Installation
          
          ### Quick Install
          ```bash
          # Install Wine runtime (if not already installed)
          flatpak install org.winehq.Platform//9 org.winehq.Platform.Compat.i386//9
          
          # Install Snickerstream
          flatpak install --user Snickerstream.flatpak
          
          # Run
          flatpak run io.github.Snickerstream
          ```
          
          See [docs/FLATPAK.md](docs/FLATPAK.md) for detailed installation instructions.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}